### PR TITLE
Adding static middleware support for windows builds

### PR DESCRIPTION
**Pull request by denyncrawford**
> It might be required to use the --allow-env flag

### CODE REVIEW

**Comment by Caesar2011** [comment]
Thanks, I will review this change, specially with `--allow-env`. Looks promising :D

**Comment by Caesar2011** [comment]
Fixed and commited. Due to a large restructure if processed it by myself. Fixed it for ViewEngine as well :D

**Comment by denyncrawford** [comment]
I will definitely not open a new issue haha, but although you could add compatibility with previous versions, it seems that the correct value of `Deno.build.os` for newer versions (like 0.41.0) is `win` and no longer `windows`. Excuse my English, it is a work in progress.

https://github.com/Caesar2011/denotrain/blob/0ffd2cfab9ac495b8d80aa046dd9340ac1bd4b17/middleware/static/mod.ts#L8

**Comment by denyncrawford** [comment]
@Caesar2011 It seems like it changed again at 0.42.0, forget that, I'm missing something, or probably deno is still too raw to trust the API.

**Comment by Caesar2011** [comment]
Yesit does. Already adjusted :D Try Denotrain 0.2.0

**Pull request closed without merging**
